services:
    mariadb:
        image: 'mariadb:latest'
        container_name: shop-mariadb
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
    php-fpm:
        build: phpdocker/php-fpm
        container_name: shop-php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
    nginx:
        image: 'nginx:alpine'
        container_name: shop-nginx
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${APP_PORT:-80}:80'
